const textAnim = document.querySelector("h1");

new Typewriter (textAnim, {
    deleteSpeed: 40
})
.changeDelay(50)
.typeString('Je suis Roland APPERT')
.pauseFor(300)
.typeString(', Dev Full-Stack !')
.pause(1000)
.deleteChars(13)
.typeString('<span style="color: #D84923"> <strong>HTML</strong> !')
.pause(1000)
.deleteChars(6)
.typeString('<span style="color: #2091EB"> CSS</strong> !')
.pause(1000)
.deleteChars(5)
.typeString('<span style="color: #3EAF7C"> Vue</strong> !')
.pause(1000)
.deleteChars(5)
.typeString('<span style="color: #89BB3C"> Node</strong> !')
.pause(1000)
.deleteChars(6)
.typeString('<span style="color: #EAD41C"> JavaScript</strong> !')
.pause(1000)
.deleteChars(12)
.typeString('<span style="color: #E3A652"> MySQL, MongoDb</strong> !')
.pause(1000)
.deleteChars(16)
.typeString('<span style="color: #2966AF"> Application M.E.V.N</strong> !')
.start()